### PR TITLE
Fix-n-clean

### PR DESCRIPTION
**Pull request by Krakinou**
- Add auto-updater for checksum
- remove automatic version in url
- remove ynh_clean_setup

### CODE REVIEW

**Comment by Krakinou** [comment]
!testme

**Comment by tituspijean** [comment]
Phew, it worked. https://github.com/YunoHost-Apps/retroarch_ynh/actions/runs/2343619988

**Comment by Krakinou** [comment]
I assumed you already knew it :)

**Comment by tituspijean** [comment]
By launching the script manually yes, but with the automated Action itself, err... no. 😅

**Pull request merged**
