### PR TITLE
Fix and clean

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem

- CI fails due to corrupt source
- `app.src.default` file is nice, but if the checksum is not updated it is useless 😢 

## Solution

- Use a standard `app.src` with fixed source address and updated checksum.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by Krakinou** [comment]
Well, as you can see if you look at the sources, they sometimes recompile/reupload a new 7z file without changing version, which drives the sha256 sum to be wrong (here, they updated it on 02/05 on https://buildbot.libretro.com/stable/1.10.3/emscripten while the 1.10.3 version was release somewhere around mid-april, I don't know why and this drives me crazy)

The strange thing is that I didn't get any warning that the CI was failing while I do for other applications I maintain. The mail used to when the maintainer is the one in the manifest.json right?

I rather stick to my app.default.src (unless you tell me there is a strong incentive to not doing so), which is not very complicated to understand and avoid the hassle to change the version number in still another place (By the way this would be a nice core feature for packagers)

**Comment by tituspijean** [comment]
> I don't know why and this drives me crazy

Yeah, that's quite dirty... I have tried to ask them about it on their Discord server, to no avail.

> The strange thing is that I didn't get any warning that the CI was failing while I do for other applications I maintain. The mail used to when the maintainer is the one in the manifest.json right?

No, I think that's in `check_process`.

> I rather stick to my app.default.src (unless you tell me there is a strong incentive to not doing so), which is not very complicated to understand and avoid the hassle to change the version number in still another place (By the way this would be a nice core feature for packagers)

I completely understand why you are doing that, but it's a bit unclean too. 😛 
I can however write up an auto-updater script that will handle most of the issue. I will open a PR for that.

**Review by Krakinou — APPROVED** [review]

**Pull request merged**
